print("{:5}{}".format("Name: ", "Jesus Juarez"))
print("{:5}{}".format("Age: ", "18 years"))
print("{:5}{}".format("Height: ", "1.65"))
print("-----------------------")
print("{:5}{}".format("Drivers´s License: : ", "False"))
print("-----------------------")
print("{:5}{}".format("ID: ", "193111675"))